config/routes.rb
Rails.application.routes.draw do

  root 'gifts#index'
  get '/login' => 'sessions#new'
  resource :session, only: [:create, :destroy]
  resources :users
  resources :nonprofits do
    resources :gifts
  end

  get '/gifts' => 'gifts#index'
  get '/profile' => 'sessions#index'
  get '/admin/users' => 'users#index'
  get '/gifts/individual' => 'gifts#individual'
  get '/gifts/business' => 'gifts#business'
  get '/all_nonprofits' => 'nonprofits#all_nonprofits'
  post '/gifts/search' => 'gifts#search'







end

app/models/gift.rb
class Gift < ActiveRecord::Base
  model_name.instance_variable_set(:@route_key, 'gift')
  belongs_to :nonprofit
  has_one :user, through: :nonprofit
  validates :body, presence: true
end

app/models/nonprofit.rb
class Nonprofit < ActiveRecord::Base
  belongs_to :user
  has_many :gifts, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base

 has_secure_password
 has_many :nonprofits
 has_many :gifts, through: :nonprofits
 validates :email, presence: true, uniqueness: true
 validates :first_name, presence: true
 validates :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

    def current_user
      @current_user ||= User.find_by(id: session[:user_id])
    end

    def logged_in?
      current_user.present?
    end

end

app/controllers/gifts_controller.rb
class GiftsController < ApplicationController

  before_action :load_all_gifts

  def index
  end

  def individual
  end

  def business
  end

  def search
    search = params[:q]
    @gifts = Gift.where('lower(body) like ?', "%#{search}%")
  end


  def new
    @gift = Gift.new
    @user = User.find(session[:user_id])
    @user_type = @user.user_type
  end

  def show
    @gift = Gift.find(params[:id])
    @nonprofit = Nonprofit.find(params[:nonprofit_id])
  end

  def destroy
    gift = Gift.find(params[:id])
    nonprofit = Nonprofit.find(params[:nonprofit_id])
    gift.delete
    redirect_to nonprofit_path(nonprofit)
  end

  def create
    gift = Gift.create(gift_params)
    nonprofit = nonprofit.find(params[:nonprofit_id])
    gift.nonprofit_id = params[:nonprofit_id]
    gift.save
    redirect_to nonprofit_path(nonprofit)
  end

  def edit
    @gift = Gift.find(params[:id])
    if @gift.user.email == session[:user_email] || admin?
      render :edit
    else
      redirect_to root_path
    end
  end

  def update
    nonprofit = Nonprofit.find(params[:nonprofit_id])
    gift = Gift.find(params[:id])
    gift.update(gift_params)
    redirect_to nonprofit_gift_path(nonprofit, gift)
  end

  helper_method :authorized?
  helper_method :admin?

  def authorized?
    current_user_email = @gift.user.email
    sessions_email = session[:user_email]
    current_user_email == sessions_email
  end

  def admin?
    session[:user_role] == "admin"
  end

  def load_all_gifts
    @gifts = Gift.all.reverse
  end

  private

  def gift_params
    params.require(:gift).permit(:body, :user_type)
  end


end

app/controllers/nonprofits_controller.rb
class NonprofitsController < ApplicationController
  before_action :load_user, only: [:index, :create, :destroy, :update,]
  before_action :load_nonprofit, only: [:show, :edit]

  def index
    @user = User.find(session[:user_id])
  end

  def new
    @nonprofit = Nonprofit.new
    @user_id = session[:user_id]
    @user = User.find(@user_id)
    if @user.user_type == "individual"
      render :individual_form
    elsif @user.user_type == "company"
      render :company_form
    else
      redirect_to root_path
    end
  end

  def show
    if @nonprofit.user.user_type == "company"
      render :company_nonprofit
    elsif @nonprofit.user.user_type == "individual"
      render :individual_nonprofit
    else
      redirect_to root_path
    end
  end

  def all_nonprofits
    @nonprofits = Nonprofit.all
    render :all_nonprofit
  end

  def edit
    if @nonprofit.user.email == session[:user_email] || session[:user_role] == "admin"
      if @nonprofit.user.user_type == "individual"
      render :edit_individual
      else
      render :edit_company
      end
    else
      redirect_to root_path
    end
  end

  def update
    nonprofit = Nonprofit.find(params[:id])
    nonprofit.update(nonprofit_params)
    redirect_to nonprofit_path(nonprofit)
  end

  def destroy
    nonprofit = Nonprofit.find(params[:id])
    user = nonprofit.user_id
    nonprofit.destroy
    redirect_to user_path(user)
  end

  def create
    user = User.find(session[:user_id])
    nonprofit = Nonprofit.create(nonprofit_params)
    nonprofit.user = user
    nonprofit.save
    redirect_to user_path(user)
  end

  def load_nonprofit
    @nonprofit = Nonprofit.find(params[:id])
  end

  def authorized?
    current_user_email = @nonprofit.user.email
    sessions_email = session[:user_email]
    current_user_email == sessions_email
  end

  def admin?
    session[:user_role] == "admin"
  end

  helper_method :authorized?
  helper_method :admin?

  private

  def nonprofit_params
    params.require(:nonprofit).permit(:address, :description, :business_name)
  end


  def load_user
    @user = User.find(session[:user_id])
  end

  def load_nonprofit
    @nonprofit = Nonprofit.find(params[:id])
  end



end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def index
    if session[:user_id]
      user = User.find(session[:user_id])
      session[:user_email] = user.email
      session[:user_role] = user.role
      redirect_to(user_path(user))
    else
    redirect_to login_path
    end
  end

  def create
    user = User.find_by(email: params[:email])
    user = user.authenticate(params[:password]) if user
      if user
        session[:user_id] = user.id
        session[:user_email] = user.email
        session[:user_role] = user.role
        redirect_to(user_path(user))
       else
        flash[:error] = "Sorry! Your password or username is wrong. Please try again!"
        redirect_to(login_path)
      end
  end

  def destroy
    session[:user_id] = nil
    redirect_to(root_path)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_action :load_user, only: [:show, :edit, :destroy, :update,]
before_action :authenticate, only: [:show, :edit, :destroy, :update,]
before_action :authorize, only: [:show, :edit, :destroy, :update,]


  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    @user.user_type = params[:user_type]
    @user.save
    session[:user_id] = @user.id
    session[:user_email] = @user.email
    session[:user_role] = @user.role
    redirect_to user_path(@user)
  end

  def destroy
    user = User.find(params[:id])
    user.delete
    session[:user_id] = nil
    session[:user_email] = nil
    session[:user_role] = nil
    redirect_to root_path
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    user.update(user_params)
    user.save
    redirect_to user_path(user)
  end

  private
  def user_params
    params.require(:user).permit(:password, :first_name, :last_name, :email, :phone, :company, :user_type)
  end

  def load_user

    @user = User.find_by(id: params[:id])
    redirect_to root_path if !@user

  end

  def authenticate
    redirect_to root_path if !logged_in?
  end

  def authorize
    if current_user != @user
      redirect_to user_path(current_user)
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    if session[:user_id]
      user = User.find(session[:user_id])
      redirect_to(user_path(user))
    else
    redirect_to login_path
  end
  end
end

app/views/gifts/business.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <h1>Show all the gifts from companies</h1>
      <%= form_tag('/gifts/search', method: "post") do %>
        <%= label_tag(:q, "Search for:") %>
        <%= text_field_tag(:q) %>
        <%= submit_tag("Search") %>
      <% end %>
  </head>
    <body>
      <%= link_to("Sort by individuals", gifts_individual_path) %> <br>
      <%= link_to("Sort by businesses", gifts_business_path) %>
        </br>
        </br>
          <div class="row">
            <ul>
              <% @gifts.each do |gift| %>
                <% if gift.user.user_type == "company" %>
                  <li class="col-sm-9 col-md-3">
                    <div class ="thumbnailz">
                      <div class="caption"  >
                        <%= gift.body%>
                          </br><br>
                            <p> <%= button_to("My Nonprofit", nonprofit_path(gift.nonprofit_id), class: 'btn btn-large btn-primary', method: :get)  %></p>
                  </li>
                <% end %>
                  <% end %>
            </ul>
          </div>
                    </div>
                      </div>

    </body>
</html>

app/views/gifts/edit.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <h1>Edit Gift</h1>
  </head>
    <body>
      <%= form_for(@gift, :url=> {:action=> (@gift.new_record? ? 'create' : 'update')}) do |f| %>
        <p>Enter Gift</p>
        <%= f.text_field :body %>
        </br>
        <%= f.submit "update" %>
      <% end %>
    </body>
</html>

app/views/gifts/index.html.erb
<!DOCTYPE html>
  <html lang="en" img src="http://www.freeimages.com/pic/l/k/kr/krappweis/1409825_37790746.jpg">
    <head>
      <meta charset="UTF-8">
      <canvas id="canvas"></canvas>
    </head>
      <body>
        <p><%= form_tag('/gifts/search', method: "post") do %>
            <%= label_tag(:q, "Search for:") %>
            <%= text_field_tag(:q) %>
            <%= submit_tag("Search") %>
          <% end %>
        </p>
              <div class="row">
                <ul>
                <% @gifts.each do |gift| %>
                  <li class="col-sm-6 col-sm-6">
                    <% if gift.user.user_type == "company" %>
                            <div class="button">
                      <div class ="thumbnailz">
                    <% else %>
                    <div class="button">
                      <div class ="thumbnailz">
                    <% end %>
                      <div class="caption">
                        <%= gift.body%>
                        <br>
                        <%= gift.gift_type %>
                          </br><br>
                          <div class="clickable">
                      <%= button_to("Send It", nonprofit_path(gift.nonprofit_id), class: 'btn btn-large btn-primary', method: :get)  %>
                    </div>
                    </div>
                  </div>
                  </li>
                    <% end %>
                </ul>
              </div>
                      </div>
                      </div>
      </body>
  </html>

app/views/gifts/individual.html.erb
<!DOCTYPE html>
  <html lang="en">
    <head>
      <meta charset="UTF-8">
      <h1>Showing All the Gifts from Individuals </h1>
    </head>
      <body>
        <%= form_tag('/gifts/search', method: "post") do %>
          <%= label_tag(:q, "Search for:") %>
          <%= text_field_tag(:q) %>
          <%= submit_tag("Search") %>
        <% end %>
          <%= link_to("Sort by individuals", gifts_individual_path) %> <br>
          <%= link_to("Sort by businesses", gifts_business_path) %>
          </br>
          </br>
            <div class="row">
              <ul>
                <% @gifts.each do |gift| %>
                <% if gift.user.user_type == "individual" %>
                  <li class="col-sm-9 col-md-3">
                    <div class ="thumbnailx">
                      <div class="caption"  >
                        <%= gift.body%>
                          </br><br>
                        <p> <%= button_to("My Nonprofit", nonprofit_path(gift.nonprofit_id), class: 'btn btn-large btn-primary', method: :get)  %></p>
                  </li>
                <% end %>
                <% end %>
              </ul>
            </div>
                    </div>
                      </div>
      </body>
    </html>

app/views/gifts/new.html.erb
<!DOCTYPE html>
  <html lang="en">
    <head>
      <meta charset="UTF-8">
      <h1>Make a New Gift!</h1>
    </head>
      <body>
        <%= form_for(@gift, :url=> {:action=> (@gift.new_record? ? 'create' : 'update')}) do |f| %>
          <p>What's your gift?</p>
          <%= f.text_field :body %>
          <%= f.text_field :gift_type %>
          <%= f.hidden_field :user_type, :value => @user_type %>
          </br><br>
          <%= f.submit "Create Gift!" %>
        <% end %>
      </body>
  </html>

app/views/gifts/search.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <h1>Showing All the Gifts</h1>
  </head>
    <body>
      <%= form_tag('/gifts/search', method: "post") do %>
        <%= label_tag(:q, "Search for:") %>
        <%= text_field_tag(:q) %>
        <%= submit_tag("Search") %>
      <% end %>
        <%= link_to("Sort by individuals", gifts_individual_path) %>
        <%= link_to("Sort by businesses", gifts_business_path) %>
          <div class="row">
            <ul>
              <% @gifts.each do |gift| %>
                <li class="col-sm-9 col-md-3">
                  <% if gift.user.user_type == "company" %>
                    <div class ="thumbnailz">
                  <% else %>
                    <div class ="thumbnailx">
                  <% end %>
                    <div class="caption"  >
                    <%= gift.body%>
                    </br><br>
                    <p><%= button_to("My NonProfit", nonprofit_path(gift.nonprofit_id), class: 'btn btn-large btn-primary', method: :get)  %></p>
                </li>
                  <% end %>
            </ul>
          </div>
                  </div>
                  </div>
    </body>
</html>

app/views/gifts/show.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <div class="mikecontainer">
      <div class="text-center">
    <h1>This is your gift</h1>
  </head>
    <body>
  <br>
  <br>
      <p><%= @gift.body %></p>
      <p><%= @gift.gift_type %></p>

        </br>
            <%= link_to 'Claim this gift', nonprofit_gift_path(@nonprofit, @gift), method: :delete, data: { confirm: "Are you sure you want to delete this gift? It can't be undone!"  } %>
        </br>
            <%= link_to 'back', :back %>
    </body>
  </div>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Gift</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-navbar-inner" href="/"><img src="http://www.marieclaire.com/cm/marieclaire/images/2r/gift-guide-marie-claire-300.jpg" width="48" height="48"></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
    <li> <%= link_to("Profile", "/profile")%></li>
    <li><%= link_to("All gifts", gifts_path) %></li>
        </li>
      </ul>
      <form class="navbar-form navbar-right" role="search">
        <div class="form-group" >
        </div>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to( "logout",session_path, method: 'delete') %>
        <li class="dropdown">
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


<%= yield %>
</body>
</html>

app/views/nonprofits/all_nonprofits.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <h1>These are the Non-Profits you created</h1>
  </head>
    <body>
      <% @nonprofits.each do |nonprofit| %>
      <%= link_to(nonprofit.description, nonprofit_path(nonprofit)) %>
      </br>
      <% end %>
    </body>
  </html>

app/views/nonprofits/company_form.html.erb
<!DOCTYPE html>
  <html lang="en">
    <head>
      <meta charset="UTF-8">
      <title>Document</title>
    </head>
      <body>
        <div class="mikecontainer">
          <p>FORM FOR A COMPANY TO CREATE A NonProfit</p>
            <%= form_for @nonprofit do |f| %>
              </br>
              <p>Business name</p>
              <%= f.text_field :business_name %>
              </br>
              <%= f.submit "submit" %>
            <% end %>
        </div>
      </body>
  </html>

app/views/nonprofits/company_nonprofit.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>COMPANY Nonprofit</title>
  </head>
    <body>
        <div class="text-center">
          <div class="mikecontainer">
      <%= @nonprofit.business_name %></br>
      <%= @nonprofit.address %></br>
      <%= @nonprofit.description %></br>


      </br></br><br><br>
            Gifts for this nonprofit
            </br>
              <% @nonprofit.gifts.each do |gift| %>
                <%= link_to(gift[:body], nonprofit_gift_path(@nonprofit, gift)) %>
                  </br>
              <% end %>
                  </br>
              <% if authorized? || admin? %>
                <%= link_to("Edit this nonprofit", edit_nonprofit_path(@nonprofit)) %>
                  </br>
                <%= link_to("Make a new gift for this nonprofit", new_nonprofit_gift_path(@nonprofit)) %>
                  </br>
                <%= link_to 'Delete this nonprofit', @nonprofit, method: :delete, data: { confirm: "Are you sure you want to delete this nonprofit? It can't be undone!"  } %>
                  </br>
              <% end %>
                <%= link_to 'Back', :back %>

        </div>
          </div>

    </body>
</html>

app/views/nonprofits/edit.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
      <h1>EDIT YOUR NONPROFITFORM</h1>
  </head>
    <body>
      <%= form_for @nonprofit do |f| %>
      <p>Enter Business Name</p>
        <%= f.text_field :business_name %>
          </br>
        <p>Enter Address</p>
        <%= f.text_field :address %>
          </br>
        <p>Enter your description</p>
        <%= f.text_field :description %>
          </br>
        <%= f.submit "update" %>
      <% end %>
    </body>
</html>

app/views/nonprofits/edit_company.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Document</title>
    <h1>Edit Your Company</h1>
  </head>
    <body>
      <div class="mikecontainer">
        <%= form_for @nonprofit do |f| %>
          <p>Business name</p>
          <%= f.text_field :business_name %>
            </br>
          <p>Business location</p>
          <%= f.text_field :business_location %>
            </br>
          <p>Business Description</p>
          <%= f.text_field :business_description %>
            </br><br>
          <%= f.submit "submit" %>
        <% end %>
      </div>
    </body>
</html>

app/views/nonprofits/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Document</title>
    <h1>My NonProfit</h1>
  </head>
    <body>
      <div class="text-center">
        <div class="mikecontainer">
          <% if @user.nonprofits.empty? == false %>
          <% @user.nonprofits.each do |nonprofit| %>
            <div class="logincontainer">
              <%= link_to(nonprofit[:nickname],nonprofit_path(nonprofit)) %>
      </div>
                </br>
          <% end %>
          <% else %>
                    <p>Whoa! Looks like you haven't made a nonprofit yet! <%= link_to("Make one!", new_nonprofit_path) %></p>
          <%end %>
                </br>
          <%= link_to 'Back', :back %>
            </div>
    </body>
</html>

app/views/nonprofits/individual_nonprofit.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <div class="mikecontainer">
      <div class="text-center">
        <h1>Gifts from this nonprofit</h1>
  </head>
    <body>
        <h3>Deliver To:</h3><br>    <%= @nonprofit.address %></br><br>
        <h3>Where its going:</h3>  <br>   <%= @nonprofit.business_name %></br>
        <%= @nonprofit.description %></br>

        <h2>Choose a Gift</h2>
        <% @nonprofit.gifts.each do |gift| %>
          <%= link_to(gift[:body], nonprofit_gift_path(@nonprofit, gift)) %>
            </br>
        <% end %>
            </br>
        <% if authorized? || admin? %>
          <%= link_to("Edit this nonprofit", edit_nonprofit_path(@nonprofit)) %>
            </br>
          <%= link_to("Make a new gift for this nonprofit", new_nonprofit_gift_path(@nonprofit)) %>
            </br>
          <%= link_to 'Delete this nonprofit', @nonprofit, method: :delete, data: { confirm: "Are you sure you want to delete this nonprofit? It can't be undone!"  } %>
            </br>
        <% end %>
          <%= link_to 'Back', :back %>
      </div>
    </div>
    </body>
</html>

app/views/nonprofits/new.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <h1>New nonprofit</h1>
  </head>
    <body>
      <div class="mikecontainer">
        <%= form_for @nonprofit do |f| %>
            Enter Business-Name
            <%= f.text_field :Business_name %>
            <br>
            Address
          <%= f.text_field :address %>
            </br>
            Enter Description
          <%= f.text_field :description %>
            </br>
          <%= hidden_field_tag(:userid, @user_id) %>
          <%= f.submit "create nonprofit!" %>
        <% end %>

          <%= link_to 'Back', :back %>
      </div>
</body>
</html>

app/views/nonprofits/show.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
  </head>
    <body>
      <div class="mikecontainer">
        Description:
        <%= @nonprofit[:business_name] %>
        <%= @nonprofit[:address] %>
        <%= @nonprofit[:description] %>

          </br>
          </br>
        Gifts BELOW:
          </br>
          </br>
            <div class="text-center">
              <% @nonprofit.gifts.each do |gift| %>
                <%= link_to(gift[:body], nonprofit_gift_path(@nonprofit gift)) %>

              <% end %>
      </div>
              </br>
              </br>
              </br>
                <% if authorized? || admin? %>
                  <%= link_to("Edit this nonprofit", edit_nonprofit_path(@nonprofit)) %>
                    </br>
                  <%= link_to("Make a new gift for this nonprofit", new_nonprofit_gift_path(@nonprofit)) %>
                    </br>
                  <%= link_to 'Delete this nonprofit', @nonprofit, method: :delete, data: { confirm: "Are you sure you want to delete this nonprofit? It can't be undone!"  } %>
                    </br>
                <% end %>
                  <%= link_to 'Back', :back %>
            </div>
    </body>
</html>

app/views/users/edit.html.erb
<!DOCTYPE html>
<html lang="en">
<div class="mikecontainer">
  <div class="text-center">
  <head>
    <meta charset="UTF-8">
  </head>
    <body>
    <h1>Edit your User profile</h1>
      <%= form_for @user do |f| %>
        <p>Enter email</p>
        <div class="login2">
        <%= f.text_field :email %>
        </div>
        <p>Enter first name</p>
        <div class="login2">
        <%= f.text_field :first_name %>
        </div>
        <p>Enter last name</p>
        <div class="login2">
        <%= f.text_field :last_name %>
        </div>
        <p>Enter phone #</p>
        <div class="login2">
        <%= f.text_field :phone %>
        </div>
          </br><br>
          <div class="login2">
        <%= f.submit "update" %>
      </div>
      <% end %>
    </body>
  </div>
</div>
</html>

app/views/users/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <h1>ALL USERS</h1>
</head>
  <body>
  <% @users.each do |user| %>
    <%= link_to(user.first_name, user_path(user)) %>
    <%= link_to(user.last_name, user_path(user)) %>
      </br>
  <% end %>
  </body>
</html>

app/views/users/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
</head>
  <body>
            <div class="mikecontainer">
  <div class="text-center">
  <h1>Create an account!</h1>
  <br>
    <%= form_for @user do |f| %>
      <p>Enter email</p>
      <div class="login">
      <%= f.text_field :email %>
      </div>
      <p>Enter first name</p>
      <div class="login">
      <%= f.text_field :first_name %>
      </div>
      <p>Enter last name</p>
      <div class="login">
      <%= f.text_field :last_name %>
      </div>
      <p>Enter phone #</p>
      <div class="login">
      <%= f.text_field :phone %>
    </div>
      <p>Enter password</p>
      <div class="login">
      <%= f.password_field :password %>
    </div>
      <p>Confirm password</p>
      <div class="login">
      <%= f.password_field :password_confirmation %>
    </div>
      <p>Are you a company?</p>
      <p>Yes</p>
      <%= radio_button_tag(:user_type, "company") %>
      <p>No</p>
      <%= radio_button_tag(:user_type, "individual") %>
      </br>
      <%= f.submit "create account!" %>
    <% end %>
  </div>
  </body>
</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html lang="en">
<div class="mikecontainer">
  <head>
    <h1>Hey, <%= @user.first_name %>!</h1>
    <meta charset="UTF-8">
  </head>
    <body>
      <%= link_to("All gifts", gifts_path) %>
        <br>
      <%= link_to( "Edit your profile", edit_user_path ) %>
        <br>
      <%= link_to 'Delete Account', @user, method: :delete, data: { confirm: 'Are you sure?' } %>
      <br>
    </body>
  </div>
</html>

app/views/welcome/index.html.erb
WELCOME SCREEN
    </br>
  <%= link_to("login", login_path) %>
    </br>
  <%= link_to("create an account",new_user_path) %>